// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: files_notifications.sql

package database

import (
	"context"
)

const addFile2Notification = `-- name: AddFile2Notification :exec
INSERT INTO files_notifications(file_id, note_id)
VALUES (?, ?)
`

type AddFile2NotificationParams struct {
	FileID string
	NoteID int64
}

func (q *Queries) AddFile2Notification(ctx context.Context, arg AddFile2NotificationParams) error {
	_, err := q.db.ExecContext(ctx, addFile2Notification, arg.FileID, arg.NoteID)
	return err
}

const removeFileFromNotification = `-- name: RemoveFileFromNotification :exec

DELETE FROM files_notifications 
WHERE file_id = ? AND note_id = ?
`

type RemoveFileFromNotificationParams struct {
	FileID string
	NoteID int64
}

func (q *Queries) RemoveFileFromNotification(ctx context.Context, arg RemoveFileFromNotificationParams) error {
	_, err := q.db.ExecContext(ctx, removeFileFromNotification, arg.FileID, arg.NoteID)
	return err
}

const removeFilesOfNotifications = `-- name: RemoveFilesOfNotifications :exec

DELETE FROM files_notifications 
WHERE note_id = ?
`

func (q *Queries) RemoveFilesOfNotifications(ctx context.Context, noteID int64) error {
	_, err := q.db.ExecContext(ctx, removeFilesOfNotifications, noteID)
	return err
}
