// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: files_reports.sql

package database

import (
	"context"
)

const addFile2Report = `-- name: AddFile2Report :exec
INSERT INTO files_reports(file_id, report_id)
VALUES (?, ?)
`

type AddFile2ReportParams struct {
	FileID   string
	ReportID int64
}

func (q *Queries) AddFile2Report(ctx context.Context, arg AddFile2ReportParams) error {
	_, err := q.db.ExecContext(ctx, addFile2Report, arg.FileID, arg.ReportID)
	return err
}

const removeFileFromReport = `-- name: RemoveFileFromReport :exec

DELETE FROM files_reports 
WHERE file_id = ? AND report_id = ?
`

type RemoveFileFromReportParams struct {
	FileID   string
	ReportID int64
}

func (q *Queries) RemoveFileFromReport(ctx context.Context, arg RemoveFileFromReportParams) error {
	_, err := q.db.ExecContext(ctx, removeFileFromReport, arg.FileID, arg.ReportID)
	return err
}

const removeFilesOfReport = `-- name: RemoveFilesOfReport :exec

DELETE FROM files_reports 
WHERE report_id = ?
`

func (q *Queries) RemoveFilesOfReport(ctx context.Context, reportID int64) error {
	_, err := q.db.ExecContext(ctx, removeFilesOfReport, reportID)
	return err
}
