-- +goose Up
CREATE TABLE operators(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    begin_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_at TEXT NOT NULL,
    police_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    center_id INTEGER NOT NULL REFERENCES centers(id) ON DELETE CASCADE
);

-- +goose Down
DROP TABLE operators;